site_name: Duon Route
copyright: © 2023 ebene fünf GmbH
nav:
  - index.md
theme:
	name: duon
repo_url: https://github.com/duon/router
extra:
	project: Route
plugins:
	- search
	- macros:
		module_name: docs/main